# Generated by Django 3.2.4 on 2021-07-28 04:27

import Products.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('price', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('availability', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(default=False)),
                ('image1', models.ImageField(default='default.jpg', upload_to=Products.models.upload_product_image_path)),
                ('image2', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=Products.models.upload_product_image_path)),
                ('image3', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=Products.models.upload_product_image_path)),
                ('image4', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=Products.models.upload_product_image_path)),
                ('video1', models.FileField(blank=True, default='default.mp4', null=True, upload_to=Products.models.upload_product_video_path)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
